name: ?? Create an issue
description: Already authenticated? Go ahead!
body:
  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Tell us what's on your mind.
    validations:
      required: true
